#include "cpu/cpu.h"
#include "cpu/cpu-inst.h"

CPUInst inst_table[256];

void cpu_inst_define() {
    DEF_INST(0x69, OP_ADC, ADDR_IMMEDIATE, 2, 2);
    DEF_INST(0x65, OP_ADC, ADDR_ZEROPAGE, 2, 3);
    DEF_INST(0x75, OP_ADC, ADDR_ZEROPAGEX, 2, 4);
    DEF_INST(0x6D, OP_ADC, ADDR_ABSOLUTE, 3, 4);
    DEF_INST(0x7D, OP_ADC, ADDR_ABSOLUTEX, 3, 4);
    DEF_INST(0x79, OP_ADC, ADDR_ABSOLUTEY, 3, 4);
    DEF_INST(0x61, OP_ADC, ADDR_INDIRECTX, 2, 6);
    DEF_INST(0x71, OP_ADC, ADDR_INDIRECTY, 2, 5);

    DEF_INST(0xE9, OP_SBC, ADDR_IMMEDIATE, 2, 2);
    DEF_INST(0xE5, OP_SBC, ADDR_ZEROPAGE, 2, 3);
    DEF_INST(0xF5, OP_SBC, ADDR_ZEROPAGEX, 2, 4);
    DEF_INST(0xED, OP_SBC, ADDR_ABSOLUTE, 3, 4);
    DEF_INST(0xFD, OP_SBC, ADDR_ABSOLUTEX, 3, 4);
    DEF_INST(0xF9, OP_SBC, ADDR_ABSOLUTEY, 3, 4);
    DEF_INST(0xE1, OP_SBC, ADDR_INDIRECTX, 2, 6);
    DEF_INST(0xF1, OP_SBC, ADDR_INDIRECTY, 2, 5);

    DEF_INST(0x29, OP_AND, ADDR_IMMEDIATE, 2, 2);
    DEF_INST(0x25, OP_AND, ADDR_ZEROPAGE, 2, 3);
    DEF_INST(0x35, OP_AND, ADDR_ZEROPAGEX, 2, 4);
    DEF_INST(0x2D, OP_AND, ADDR_ABSOLUTE, 3, 4);
    DEF_INST(0x3D, OP_AND, ADDR_ABSOLUTEX, 3, 4);
    DEF_INST(0x39, OP_AND, ADDR_ABSOLUTEY, 3, 4);
    DEF_INST(0x21, OP_AND, ADDR_INDIRECTX, 2, 6);
    DEF_INST(0x31, OP_AND, ADDR_INDIRECTY, 2, 5);

    DEF_INST(0x09, OP_ORA, ADDR_IMMEDIATE, 2, 2);
    DEF_INST(0x05, OP_ORA, ADDR_ZEROPAGE, 2, 3);
    DEF_INST(0x15, OP_ORA, ADDR_ZEROPAGEX, 2, 4);
    DEF_INST(0x0D, OP_ORA, ADDR_ABSOLUTE, 3, 4);
    DEF_INST(0x1D, OP_ORA, ADDR_ABSOLUTEX, 3, 4);
    DEF_INST(0x19, OP_ORA, ADDR_ABSOLUTEY, 3, 4);
    DEF_INST(0x01, OP_ORA, ADDR_INDIRECTX, 2, 6);
    DEF_INST(0x11, OP_ORA, ADDR_INDIRECTY, 2, 5);

    DEF_INST(0x49, OP_EOR, ADDR_IMMEDIATE, 2, 2);
    DEF_INST(0x45, OP_EOR, ADDR_ZEROPAGE, 2, 3);
    DEF_INST(0x55, OP_EOR, ADDR_ZEROPAGEX, 2, 4);
    DEF_INST(0x4D, OP_EOR, ADDR_ABSOLUTE, 3, 4);
    DEF_INST(0x5D, OP_EOR, ADDR_ABSOLUTEX, 3, 4);
    DEF_INST(0x59, OP_EOR, ADDR_ABSOLUTEY, 3, 4);
    DEF_INST(0x41, OP_EOR, ADDR_INDIRECTX, 2, 6);
    DEF_INST(0x51, OP_EOR, ADDR_INDIRECTY, 2, 5);

    DEF_INST(0x0A, OP_ASL, ADDR_ACCUMULATOR, 1, 2);
    DEF_INST(0x06, OP_ASL, ADDR_ZEROPAGE, 2, 5);
    DEF_INST(0x16, OP_ASL, ADDR_ZEROPAGEX, 2, 6);
    DEF_INST(0x0E, OP_ASL, ADDR_ABSOLUTE, 3, 6);
    DEF_INST(0x1E, OP_ASL, ADDR_ABSOLUTEX, 3, 6);

    DEF_INST(0x4A, OP_LSR, ADDR_ACCUMULATOR, 1, 2);
    DEF_INST(0x46, OP_LSR, ADDR_ZEROPAGE, 2, 5);
    DEF_INST(0x56, OP_LSR, ADDR_ZEROPAGEX, 2, 6);
    DEF_INST(0x4E, OP_LSR, ADDR_ABSOLUTE, 3, 6);
    DEF_INST(0x5E, OP_LSR, ADDR_ABSOLUTEX, 3, 6);

    DEF_INST(0x2A, OP_ROL, ADDR_ACCUMULATOR, 1, 2);
    DEF_INST(0x26, OP_ROL, ADDR_ZEROPAGE, 2, 5);
    DEF_INST(0x36, OP_ROL, ADDR_ZEROPAGEX, 2, 6);
    DEF_INST(0x2E, OP_ROL, ADDR_ABSOLUTE, 3, 6);
    DEF_INST(0x3E, OP_ROL, ADDR_ABSOLUTEX, 3, 6);

    DEF_INST(0x6A, OP_ROR, ADDR_ACCUMULATOR, 1, 2);
    DEF_INST(0x66, OP_ROR, ADDR_ZEROPAGE, 2, 5);
    DEF_INST(0x76, OP_ROR, ADDR_ZEROPAGEX, 2, 6);
    DEF_INST(0x6E, OP_ROR, ADDR_ABSOLUTE, 3, 6);
    DEF_INST(0x7E, OP_ROR, ADDR_ABSOLUTEX, 3, 6);

    DEF_INST(0x90, OP_BCC, ADDR_RELATIVE, 2, 2);
    DEF_INST(0xB0, OP_BCS, ADDR_RELATIVE, 2, 2);
    DEF_INST(0xF0, OP_BEQ, ADDR_RELATIVE, 2, 2);
    DEF_INST(0xD0, OP_BNE, ADDR_RELATIVE, 2, 2);
    DEF_INST(0x50, OP_BVC, ADDR_RELATIVE, 2, 2);
    DEF_INST(0x70, OP_BVS, ADDR_RELATIVE, 2, 2);
    DEF_INST(0x10, OP_BPL, ADDR_RELATIVE, 2, 2);
    DEF_INST(0x30, OP_BMI, ADDR_RELATIVE, 2, 2);
}

int cpu_inst_exec() {
    ;
}
